# Generated by Django 2.2.4 on 2019-09-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190913_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_super_admin', models.IntegerField(default=0)),
                ('api_token', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
