# Generated by Django 2.2.4 on 2019-09-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190925_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
