# Generated by Django 2.2.4 on 2019-09-30 09:29

from django.db import migrations
import django.db.models.manager


# class Migration(migrations.Migration):

#     dependencies = [
#         ('accounts', '0004_auto_20190925_0129'),
#     ]

#     operations = [
#         migrations.AlterModelManagers(
#             name='account',
#             managers=[
#                 ('accountManager', django.db.models.manager.Manager()),
#             ],
#         ),
#     ]
