# Generated by Django 2.2.4 on 2019-10-07 18:45

from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('picode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('fm', 'female'), ('ot', 'other')], max_length=2)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=user_profile.models.imageUpload)),
                ('dob', models.DateField(null=True)),
                ('company_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='user_profile.Address', verbose_name='company address')),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='user_profile.Profile')),
                ('permanent_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='user_profile.Address', verbose_name='permanent address')),
            ],
        ),
    ]
